print("Content-Type: text/html\n")
print("<html>")
print("<head><title>CGI Test</title></head>")
print("<body>")
print("<h1>Hello World!</h1>")
print("<p>")
print("This is a python script.")
print("</p>")
print("</body>")
print("</html>")
