http
{
    server
    {
        location /
        {
            root YoupiBanane;
            limit_except GET
            {
                deny all;
            }
        }

        location /put_test/*
        {
            limit_except PUT
            {
                deny all;
            }
        }
    }
}