name: webserv check
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  webserv-check:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: make
      run: make

    - name: Compilation success message
      run: echo "Compiled Successfully"

    - name: basic-webserver
      run: |
            ./webserv &
            sleep 5
            echo "==== TESTING ===="
            echo "root"
            curl -v localhost:4242/
            echo "Main Index"
            curl -v localhost:4242/index.html
            echo "Another HTML Page"
            curl -v localhost:4242/html/features.html
            echo "404 Page Not Found"
            curl -v localhost:4242/donotexist
            echo "405 Method Not Allowed"
            curl -v localhost:4242/uploads


